version: "3.4"

services:
  postgres:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-app-template
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U postgres -d postgres'"
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  adminer:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - postgres
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - net

  redis:
    image: redis:7.2-alpine
    restart: on-failure
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data
    networks:
      - net

  server:
    image: detteksie/nest-app-template
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    working_dir: /app
    ports:
      - 4000:4000
    command: [ "sh", "-c", "npm run start:dev:hmr" ]
    volumes:
      - .:/app:delegated
      - /app/node_modules
    networks:
      - net
    env_file:
      - .env
    stdin_open: true
    tty: true

volumes:
  pgdata:
  redisdata:


networks:
  net:
