export const DATABASE_URL = 'DATABASE_URL';
export const JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET';
export const JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';
export const THROTTLE_TTL = 'THROTTLE_TTL';
export const THROTTLE_LIMIT = 'THROTTLE_LIMIT';
